#!/usr/bin/env bash
# if did not give the argument ($1 boşsa), using "you" 
name=${1:-you}
echo "One for $name, one for me."
# ${parameter:-default} → "Is Zero-length or undefined variable ? if it is use default"
